#+title: DOF Design System

** About

The DOF Design System provides a set of components that compose a CSS
library, used to build pages for the Department of Finance's website
redesign. It is an opinionated set of design decisions made to address
issues facing the Department of Finance's current website. As such
this library is not intended for general-purpose use, though it can be
used as a reference for other design systems.

This repository is structured in a monorepo style, with library files
all living under the [[file:packages/index.org][packages]] directory. To ease the prototyping and
build process, the [[https://vitejs.dev/][Vite]] development environment is used.

** Principles

*** CUBE CSS

Architect CSS with the [[https://cube.fyi/][CUBE CSS]] methodology, embracing the cascading
nature of CSS to provide progressively enhanced page styling.

*** CSS variables

Use CSS variables as hooks to theme the design system. They can be
used to modify size, space, color and typography.

[[file:packages/variables/variables.org][Learn more about DOF CSS variables]]

*** Intrinsic web design

Breakpoint-based styling modifications are eschewed where possible,
favoring fluid typography and spacing, and modifying component layouts
based on the size of their container, not the viewport.


** Getting Started

If you are interested in utilizing the library, a good starting point
is to review the [[file:packages/index.org][packages documentation]]. There an overview of the
library's architecture is provided and you may browse the available
packages. Each package's documentation contains examples, usage
guidelines, and source code.

** Development

If you would like to contribute to the library, please feel free to
make a pull request.

*** Requirements

- [[https://pnpm.io/][pnpm]] package manager
- [[https://www.gnu.org/software/emacs/][GNU Emacs]] (optional) - the emacs binary is used to build the
  documentation website and extract source code from ~org~ files.

After cloning this repository, run =pnpm install= to fetch the
required dependencies and =pnpm run dev= to start the
development server.

*** Building

To build the library stylesheet run =pnpm run build=
