#+TITLE: Variables

This library utilizes [[https://developer.mozilla.org/en-US/docs/Web/CSS/--*][CSS custom properties]], adopting a naming
convention influenced by Google's [[https://m3.material.io/foundations/design-tokens/how-to-read-tokens#98e82e98-5ecd-4c5d-a03a-7d4cc5d55c20][Material design system tokens]]. The
variables are divided into a 3-tier structure: Reference, System, and
Component.

#+TOC: headlines 2

** Reference variables

Reference variables are used to hold direct property values, the value
you would give to a CSS property when not using variables.

| Prefix  | Pattern                               |
|---------+---------------------------------------|
| nyc-ref | --{prefix}-{property}{-label}{-scale} |

*** Color

Color reference variables allow you to label and scale colors used on the site.

#+begin_src css :noweb-ref ref-vars
  --nyc-ref-color-blue-50: hsla(214, 54%, 95%, 1);
  --nyc-ref-color-blue-100: hsla(207, 71%, 68%, 1);
  --nyc-ref-color-blue-200: hsla(213, 53%, 50%, 1);
  --nyc-ref-color-blue-250: hsla(213, 59%, 45%, 1);
  --nyc-ref-color-blue-500: hsla(208, 100%, 30%, 1);
  --nyc-ref-color-blue-700: hsla(210, 64%, 19%, 1);
  --nyc-ref-color-orange-500: hsla(26, 92%, 58%, 1);
  --nyc-ref-color-orange-700: hsla(25, 78%, 41%, 1);
  --nyc-ref-color-neutral-0: hsla(0, 0%, 100%, 1);
  --nyc-ref-color-neutral-100: hsla(0, 0%, 93%, 1);
  --nyc-ref-color-neutral-200: hsla(0, 0%, 80%, 1);
  --nyc-ref-color-neutral-300: hsla(0, 0%, 53%, 1);
  --nyc-ref-color-neutral-400:  hsla(0, 0%, 40%, 1);
  --nyc-ref-color-neutral-800: hsla(0, 0%, 20%, 1);
  --nyc-ref-color-neutral-900: hsla(0, 0%, 0%, 1);

  --nyc-ref-shadow-400: 4px 4px 8px hsla(0, 0%, 0%, .2);
  --nyc-ref-shadow-450: 0 4px 8px hsla(0, 0%, 0%, .2);
  --nyc-ref-shadow-500: 0 4px 4px hsla(0, 0%, 0%, .25);

  --nyc-ref-gradient-blue-100: radial-gradient(
    56.94% 119.67% at 78.96% 43.36%, #E6F4FF 0%, #BDE3FF 100%
  );
  /* warning: gradient uses a rotation that is not supported by
     CSS and may not behave as expected */
#+end_src

*** Size

The below size variables are used for fluid =font-size= and are
generated from the [[https://utopia.fyi][Utopia]] calculator ([[https://utopia.fyi/type/calculator?c=320,16,1.2,1024,18,1.25,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12][scale source]])

#+begin_src css :noweb-ref ref-vars
  /* Step -2: 11.11px → 11.52px */
  --nyc-ref-dimension-size-step--2: clamp(0.69rem, calc(0.68rem + 0.06vw), 0.72rem);

  /* Step -1: 13.33px → 14.40px */
  --nyc-ref-dimension-size-step--1: clamp(0.83rem, calc(0.80rem + 0.15vw), 0.90rem);

  /* Step 0: 16.00px → 18.00px */
  --nyc-ref-dimension-size-step-0: clamp(1.00rem, calc(0.94rem + 0.28vw), 1.13rem);

  /* Step 1: 19.20px → 22.50px */
  --nyc-ref-dimension-size-step-1: clamp(1.20rem, calc(1.11rem + 0.47vw), 1.41rem);

  /* Step 2: 23.04px → 28.13px */
  --nyc-ref-dimension-size-step-2: clamp(1.44rem, calc(1.30rem + 0.72vw), 1.76rem);

  /* Step 3: 27.65px → 35.16px */
  --nyc-ref-dimension-size-step-3: clamp(1.73rem, calc(1.51rem + 1.07vw), 2.20rem);

  /* Step 4: 33.18px → 43.95px */
  --nyc-ref-dimension-size-step-4: clamp(2.07rem, calc(1.77rem + 1.53vw), 2.75rem);

  /* Step 5: 39.81px → 54.93px */
  --nyc-ref-dimension-size-step-5: clamp(2.49rem, calc(2.06rem + 2.15vw), 3.43rem);
#+end_src

*** Space

The below space variables are used for fluid =margin= and =padding= and
are generated from the [[https://utopia.fyi][Utopia]] calculator ([[https://utopia.fyi/space/calculator?c=320,16,1.2,1024,18,1.25,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12][scale source]])

#+begin_src css :noweb-ref ref-vars
  --nyc-sys-dimension-space-3xs: clamp(0.25rem, calc(0.22rem + 0.14vw), 0.31rem);
  --nyc-sys-dimension-space-2xs: clamp(0.50rem, calc(0.47rem + 0.14vw), 0.56rem);
  --nyc-sys-dimension-space-xs: clamp(0.75rem, calc(0.69rem + 0.28vw), 0.88rem);
  --nyc-sys-dimension-space-s: clamp(1.00rem, calc(0.94rem + 0.28vw), 1.13rem);
  --nyc-sys-dimension-space-m: clamp(1.50rem, calc(1.41rem + 0.43vw), 1.69rem);
  --nyc-sys-dimension-space-l: clamp(2.00rem, calc(1.89rem + 0.57vw), 2.25rem);
  --nyc-sys-dimension-space-xl: clamp(3.00rem, calc(2.83rem + 0.85vw), 3.38rem);
  --nyc-sys-dimension-space-2xl: clamp(4.00rem, calc(3.77rem + 1.14vw), 4.50rem);
  --nyc-sys-dimension-space-3xl: clamp(6.00rem, calc(5.66rem + 1.70vw), 6.75rem);

  /* One-up pairs */
  --nyc-sys-dimension-space-3xs-2xs: clamp(0.25rem, calc(0.11rem + 0.71vw), 0.56rem);
  --nyc-sys-dimension-space-2xs-xs: clamp(0.50rem, calc(0.33rem + 0.85vw), 0.88rem);
  --nyc-sys-dimension-space-xs-s: clamp(0.75rem, calc(0.58rem + 0.85vw), 1.13rem);
  --nyc-sys-dimension-space-s-m: clamp(1.00rem, calc(0.69rem + 1.56vw), 1.69rem);
  --nyc-sys-dimension-space-m-l: clamp(1.50rem, calc(1.16rem + 1.70vw), 2.25rem);
  --nyc-sys-dimension-space-l-xl: clamp(2.00rem, calc(1.38rem + 3.13vw), 3.38rem);
  --nyc-sys-dimension-space-xl-2xl: clamp(3.00rem, calc(2.32rem + 3.41vw), 4.50rem);
  --nyc-sys-dimension-space-2xl-3xl: clamp(4.00rem, calc(2.75rem + 6.25vw), 6.75rem);

  /* Custom pairs */
  --nyc-sys-dimension-space-s-l: clamp(1.00rem, calc(0.43rem + 2.84vw), 2.25rem);
#+end_src

** System variables

System variables introduce a semantic layer where we can provide
useful names to our Reference variables, such as a ~primary~ color or a
~base~ font.

| Prefix  | Pattern                                 |
|---------+-----------------------------------------|
| nyc-sys | --{prefix}-{property}-{label}{-variant} |

*** Color

#+begin_src css :noweb-ref sys-vars
  --nyc-sys-color-primary: var(--nyc-ref-color-blue-500);
  --nyc-sys-color-on-primary: var(--nyc-ref-color-neutral-0);
  --nyc-sys-color-primary-lighter: var(--nyc-ref-color-blue-100);
  --nyc-sys-color-on-primary-lighter: var(--nyc-ref-color-blue-700);
  --nyc-sys-color-primary-lightest: var(--nyc-ref-color-blue-50);
  --nyc-sys-color-primary-dark: var(--nyc-ref-color-blue-700);
  --nyc-sys-color-secondary: var(--nyc-ref-color-orange-500);
  --nyc-sys-color-text: var(--nyc-ref-color-neutral-800);
  --nyc-sys-color-text-light: var(--nyc-ref-color-neutral-400);
  --nyc-sys-color-link: var(--nyc-sys-color-primary, currentColor);
  --nyc-sys-color-background: var(--nyc-ref-color-neutral-0);
  --nyc-sys-color-border: var(--nyc-ref-color-neutral-100);
  --nyc-sys-color-neutral-lightest: var(--nyc-ref-color-neutral-100);
  --nyc-sys-color-neutral-light: var(--nyc-ref-color-neutral-200);
  --nyc-sys-color-neutral: var(--nyc-ref-color-neutral-300);
  --nyc-sys-color-accent: var(--nyc-sys-color-primary);
#+end_src

*** Gradient/Shadow

#+begin_src css :noweb-ref sys-vars
  --nyc-sys-gradient-primary-light: var(--nyc-ref-gradient-blue-100);
  --nyc-sys-shadow-base: var(--nyc-ref-shadow-500);
  --nyc-sys-shadow-weak: var(--nyc-ref-shadow-400);
#+end_src

*** Dimension

#+begin_src css :noweb-ref sys-vars
  --nyc-sys-dimension-page-max-width: 64rem;

  --nyc-sys-dimension-size-xs: var(--nyc-ref-dimension-size-step--2);
  --nyc-sys-dimension-size-s: var(--nyc-ref-dimension-size-step--1);
  --nyc-sys-dimension-size-m: var(--nyc-ref-dimension-size-step-0);
  --nyc-sys-dimension-size-l: var(--nyc-ref-dimension-size-step-2);
  --nyc-sys-dimension-size-xl: var(--nyc-ref-dimension-size-step-3);
  --nyc-sys-dimension-size-xxl: var(--nyc-ref-dimension-size-step-4);  

#+end_src

*** Typesetting

#+begin_src css :noweb-ref sys-vars
  --nyc-sys-line-height: 1.4;
  --nyc-sys-font-size-base: var(--nyc-ref-dimension-size-step-0);
  --nyc-sys-font-family-base: "Helvetica Neue", Helvetica, Arial, sans-serif;
#+end_src

*** Logical variables

#+begin_src css :noweb-ref sys-vars
  --ON: initial;
  --OFF: ;
#+end_src

** Component variables

Component variables are the variables that will be referenced in our
component CSS properties and these reference System variables.

| Prefix  | Pattern                                   |
|---------+-------------------------------------------|
| nyc-cmp | --{prefix}-{component}-{property}{-state} |


#+begin_src css :tangle no
  --nyc-cmp-card-background-hover: var(--nyc-sys-color-primary-light, transparent);
#+end_src

** Custom selectors

[[https://drafts.csswg.org/css-extensions/#custom-selectors][Custom selectors]] is a draft CSS specification that allows holding
multiple CSS selectors under a given name.

#+begin_src css :noweb-ref custom-selectors
  @custom-selector :--heading h1, h2, h3, h4, h5, h6;
#+end_src

** Appendix :noexport:

#+BEGIN_SRC css :tangle variables.css :noweb yes
  /* CSS variables: Reference and System */
  :root {
    /* Reference variables */
    <<ref-vars>>

    /* System variables */
    <<sys-vars>>
  }

  /* Custom selectors */
  <<custom-selectors>>
#+END_SRC
