#+title: Tabs

Tabs are a set of layered sections of content, known as tab panels,
that display one panel of content at a time. Each tab panel has an
associated tab element, that when activated, displays the panel. The
list of tab elements is arranged along one edge of the currently
displayed panel, most commonly the top edge.

** Examples

*** Basic

Accordions can be invoked in two ways: the =nyc-accordion= custom
element or adding a ~data-is="nyc-accordion"~ attribute to a desired
element. These will generate an accessible accordion markup structure
and functionality when given a heading element as a first child;
sibling elements will be added to the accordion panel. Whenever the
same heading type is encountered a new accordion group will be
created.

#+html: <div class="example-wrapper">
#+results: accordion-basic-example
#+html: </div>

#+name: accordion-basic-example
#+begin_src html :exports both :results replace html
  <nyc-accordion data-expanded="true">
    <h4>Taxes</h4>
    <p>Content about taxes</p>
    <h4>Fines</h4>
    <h5>Parking tickets</h5>
    <p>Content about parking tickets</p>
  </nyc-accordion>
#+end_src

*** Nested accordions

Nesting accordions also works as expected

#+html: <div class="example-wrapper">
#+results: accordion-nested-example
#+html: </div>

#+name: accordion-nested-example
#+begin_src html :exports both :results replace html
  <nyc-accordion>
    <h3>Assessment definitions</h3>
    <div class="flow">
      <p>
        The following alphabetical listing of terms is provided to
        help you understand property valuation and tax assessment:
      </p>
      <div data-is="nyc-accordion">
        <h4>Abatements</h4>
        <div>
          <p>
            Abatements reduce your taxes after they've been
            calculated. Different abatement programs are available
            for housing rehabilitation, revitalization and
            cooperatives and condominiums.
          </p>
        </div>
        <h4>Actual assessed value</h4>
        <div>
          <p>
            The assessed value before five year phase-in
            requirements (for some tax class 2 and all tax class 4
            properties) and/or exemptions are applied.
          </p>
        </div>
      </div>
    </div>
  </nyc-accordion>
#+end_src

** Source Code

- [[file:css.org][CSS]]
- [[file:js.org][Javascript]]
  
** References

- [[https://web.dev/building-a-tabs-component/][Building a Tabs component]]
- [[https://www.w3.org/WAI/ARIA/apg/patterns/tabs/][ARIA Authoring Practices Guide: Tabs Pattern]]
- [[https://inclusive-components.design/tabbed-interfaces/][Inclusive Components: Tabbed Interfaces]]
